export const Roboto = {
  black: 'Roboto-Black',
  blackItalic: 'Roboto-BlackItalic',
  bold: 'Roboto-Bold',
  boldCondensed: 'Roboto-BoldCondensed',
  boldCondensedItalic: 'Roboto-BoldCondensedItalic',
  boldItalic: 'Roboto-BoldItalic',
  condensed: 'Roboto-Condensed',
  italic: 'Roboto-Italic',
  light: 'Roboto-Light',
  lightItalic: 'Roboto-LightItalic',
  medium: 'Roboto-Medium',
  mediumItalic: 'Roboto-MediumItalic',
  thin: 'Roboto-Thin',
  thinItalic: 'Roboto-ThinItalic',
  regular: 'Roboto-Regular',
}
